name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.AWS_EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Deploy backend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}
        AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_PUBLIC_IP }}
      run: |
        scp -i $AWS_EC2_KEY -r backend ec2-user@$AWS_EC2_PUBLIC_IP:/home/ec2-user/backend
        ssh -i $AWS_EC2_KEY ec2-user@$AWS_EC2_PUBLIC_IP "cd /home/ec2-user/backend && nohup uvicorn main:app --host 0.0.0.0 --port 8000 &"